### ISSUE TITLE
회원 기업 인증 API

### ISSUE THREAD

**Issue by pwrwpw** [Aivle-32bit/32bit-BE#21]
### 📄 Describe

회원의 기업 인증을 위한 API를 구현합니다. 
이 API는 회원이 자신의 기업 정보를 등록하고 인증 상태를 확인할 수 있도록 합니다.

### ✅ Tasks

* [x] 파일 업로드 처리
  * [x] S3Service를 구현하여 AWS S3에 파일을 업로드하고, 프리사인드 URL을 생성합니다.
  * [x] 파일 업로드 요청 시 파일 형식 및 크기를 검증합니다.

* [x] POST /api/company-registrations: 기업 등록 요청을 처리합니다.
* [x] GET /api/company-registrations: 회원의 모든 기업 등록 정보를 조회합니다.
