### ISSUE TITLE
마이페이지 기능 추가 및 회원 도메인 수정

### ISSUE THREAD

**Issue by pwrwpw** [Aivle-32bit/32bit-BE#43]
### 📄 Describe

마이페이지 접속 시 정보를 주는 api를 만들고 회원 테이블에 imageUrl을 저장해서 프로필 사진 등록 api를 만들 예정

### ✅ Tasks

* [x] 마이페이지 정보 제공 기능 추가
* [x] 회원 엔티티 image_url 컬럼 추가
* [x] 프로필 사진 등록 기능 추가
* [x] 프로필 사진 삭제 기능 추가
* [x] 마이페이지 정보 업데이트 기능 추가
* [x] 회원 탈퇴 기능 추가
