### ISSUE TITLE
기업 보고서 도메인 생성

### ISSUE THREAD

**Issue by pwrwpw** [Aivle-32bit/32bit-BE#49]
### 📄 Describe

기업의 재무 및 SWOT 분석 정보를 저장하고 관리하기 위한 도메인 모델을 추가합니다.

### ✅ Tasks

* [x] Company 도메인 모델 수정 (필요 시)
* [x] FinancialSummary 도메인 모델 생성
* [x] CompanyInfo 도메인 모델 생성
* [x] Swot 도메인 모델 생성
* [x] MetricsSummary 도메인 모델 생성
