### ISSUE TITLE
회사 보고서 API

### ISSUE THREAD

**Issue by pwrwpw** [Aivle-32bit/32bit-BE#53]
### 📄 Describe

회사의 재무제표를 통해 보고서를 만드는 API를 만들 예정입니다.

### ✅ Tasks

* [x] DEBT, ATR, AGR, ROA, PPE 에 대한 정보를 제공한다.
* [x] Swot에 대한 정보를 제공한다.
* [x] 매출액, 당기순이익, 부채총액,자산총액 등에 대한 정보를 제공한다.
