### ISSUE TITLE
보고서 페이지 회사 검색 자동완성 기능

### ISSUE THREAD

**Issue by b-sujin** [Aivle-32bit/32bit-BE#55]
### 📄 Describe

자동 완성, 검색 기능  
➜ return : id, name, businessType

-----------------------------------------------------------------------------------------------------------------------

🔎 검색
➜ 회사명과 검색명이 완전히 일치해야 정보 return 
➜ 회사명 ≠ 검색어이거나 공백 입력 시 예외 발생 

-----------------------------------------------------------------------------------------------------------------------

💻 자동 완성  
➜ 반환할 회사 명이 존재 하지 않을 시 빈리스트 반환
➜ 회사 isDelete = True 면 검색 안되게 처리 

1️⃣ 영어 알파벳
 ➜ 'K' or 'k' 입력 시 ( 대/소문자 관계 없음 )
: [{'k'로 시작하는 회사명 'k' 다음 단어 기준으로 알파벳  or 가나다 순 정렬} , {'k'가 포함된 회사명 첫 글자 기준 알파벳 or 가나다 순 정렬}]

2️⃣ 영어 단어
➜ 'kt'라 입력 시 
: [{'kt'로 시작하는 회사명 'kt' 다음 단어 기준으로 알파벳  or 가나다 순 정렬} , {'kt'가 포함된 회사명 첫 글자 기준 알파벳 or 가나다 순 정렬}]

3️⃣ 한글 초성 
➜ 'ㅅ' 라 입력 시 
: [{'ㅅ'로 시작하는 회사명 'ㅅ' 다음 단어 기준으로 알파벳  or 가나다 순 정렬} , {'ㅅ'가 포함된 회사명 첫 글자 기준 알파벳 or 가나다 순 정렬}]
➜ 모음 입력 시 빈리스트 반환

4️⃣ 한글 단어
➜ '삼'이라 입력 시 
: [{'삼'로 시작하는 회사명 '삼' 다음 단어 기준으로 알파벳  or 가나다 순 정렬} , {'삼'가 포함된 회사명 첫 글자 기준 알파벳 or 가나다 순 정렬}]

### ✅ Tasks

- [x] 검색 기능 

- [x] isDelete = True 검색 결과로 return X

- [x] 회사 타이핑하면 실시간으로 자동완성 검색어 출력 

- [x] 자음만 입력했을 때 자동완성 검색어 출력
