### ISSUE TITLE
예상치 못한 예외 발생시 디스코드 알림

### ISSUE THREAD

**Issue by pwrwpw** [Aivle-32bit/32bit-BE#8]
### 📄 Describe

예상하지 못한 에러가 발생해서 RunTimeException을 발생할 경우
디스코드에 @everyone을 통해 알림을 전송하도록 설정

### ✅ Tasks

* [x] 디스코드 WebHook 생성
* [x] 예상하지 못한 예외시 이벤트 발생
* [x] 이벤트가 발생 될 경우 @everyone 메시지 전송
